name: C++ CI

on: [push]

jobs:
  build-ubuntu:
    name: Build (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare
      run: mkdir build/
    - name: Download GoogleTest
      run: sudo apt-get install libgtest-dev
    - name: Configure
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Release -G"Unix Makefiles" -DFAR_LANG="C++" ../
    - name: Compile
      working-directory: build
      run: cmake --build . --config Release -j 4
      
  build-windows:
    name: Build (Windows)
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Prepare
      run: mkdir build/
    - name: Download GoogleTest
      run: nuget install Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn -Version 0.17.1 -OutputDirectory packages/ -Verbosity detailed -SolutionDirectory build/
    - name: DEBUG - List content
      run: dir /s /b packages
    - name: Configure
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -DFAR_LANG="C++" ../
    - name: Compile
      working-directory: build
      run: cmake --build . --config Release -j 4
